main.js
*  Adds blank "File" menu item to the custom menu.
*  Submenu items and related functionality to be added through issues #63-#65.
=> #62 Add File menu item to custom menu

assets/js/renderer.js, index.html, main.js
*  Local branch `63...` created from local branch `62...`, which has not yet been merged into `develop`.
*  Added submenu items for JSON import and export to "File" menu item.
*  Using ipcRenderer module to communicate asynchronously from renderer process to main process.
*  Removed sidebar buttons and related functions for JSON import and export.
*  Addresses issue #63. 
=> #63 Add JSON import and export to custom menu

main.js
* Shortcuts for JSON import, JSON export and Quit.
* Addresses issue https://github.com/nexB/aboutcode-manager/issues/65
=> Add keyboard shortcuts to "File" submenu items #65

assets/js/renderer.js, index.html, main.js
* Keyboard shortcut to be added under issue #77.
* Addresses issue #75.
=> Add open-SQLite function to custom menu #75

assets/js/renderer.js, index.html, main.js
* Keyboard shortcut to be added under issue #77.
* Addresses issue #76.
=> Add save-SQLite function to custom menu #76

main.js
* Keyboard shortcuts added for open-SQLite and save-SQLite.
=> Add shortcuts to SQLite menu functions #77

main.js
=> Add shortcuts for custom menu top-level items #84

assets/js/renderer.js
=> Add JSON-focused filter to JSON-import dialog #97

assets/css/main.css, assets/js/renderer.js
* Custom class added to `main.css`, applied to directories but not
files.
=> Replace Glyphicons with Font Awesome in jsTree #55

assets/js/renderer.js
* The upload process will not start if the value of any form field
is “”.
=> Alert when upload-components field is empty #135

assets/js/renderer.js, main.js
Keyboard shortcut: `Ctrl+Shift+D` ("D" for "data" or "D3").
=> Add menu item for Chart Summary View #144

assets/js/aboutCodeDataTables.js
=> Create button to hide all columns but "Path" #158

index.html, main.js
=> Change description of Save function #126

assets/css/main.css, assets/js/aboutCodeDataTables.js
* Also added CSS in main.css to slightly reduce buttons' left/right
padding.
=> Add 'Package info' group button #91

assets/css/main.css, assets/js/aboutCodeDataTables.js
* This required setting the css width from auto to 100% and then
setting the word wrapping
Signed-off-by: Jillian Daguil <jdaguil@nexb.com>
=> Fix DataTable filter to match width of the DataTable column #194

assets/css/main.css, assets/js/aboutCodeDataTables.js
* Take jstree path selection into account when populating column
filter values
=> Filter column values based on selected directory #195

assets/app/js/aboutCodeDataTables.js
=> Fix Table View display order #134

assets/app/js/renderer.js
Fix cases where querying on jstree directory path returned similar path names.
=> Add forward slash for directory search #211

main.js
=> URLs now open in default Browser #236

index.html
=> Change field from Component to name in the modal view #250

assets/app/js/controllers/aboutCodeClueDataTable.js
=> File Extension column filter now filters by exact values

assets/app/js/controllers/aboutCodeBarChart.js
=> Bar chart filter counts now ignore directories #183

assets/app/js/controllers/aboutCodeClueDataTable.js, assets/app/js/renderer.js
=> Update column filter population on node(path) selection

assets/app/js/controllers/aboutCodeClueDataTable.js
=> Add 'Has no Value' option to Table View filters #235

assets/app/js/controllers/aboutCodeClueDataTable.js, assets/app/js/renderer.js
=> Make BarChart 'No Value Detected' clickable #280

assets/app/js/controllers/aboutCodeClueDataTable.js
=> Ignore leading/trailing/isolated whitespace #240

assets/app/css/main.css, assets/app/js/controllers/aboutCodeClueDataTable.js
=> Right-justify numeric columns #286

assets/app/js/controllers/aboutCodeScanDataTable.js
=> Update filter queries for new Copyright model

assets/app/js/controllers/aboutCodeScanDataTable.js
=> Handle true/false column filters #295

assets/app/js/renderer.js
=> Add dialog text to handle out-of-sync SQLite database files #288

assets/app/js/controllers/aboutCodeBarChart.js, assets/app/js/controllers/aboutCodeConclusionDataTable.js, assets/app/js/controllers/aboutCodeDashboard.js, assets/app/js/renderer.js
* Dashboard d3 charts update depending on selected path
* File Counts update depending on selected path
* Unique License and Copyright counts now filtered by selected path
* Package counts now filtered by selected path
Addresses: #267
=> Add TreeView to all views

assets/app/css/main.css, assets/app/js/aboutCodeDB.js, assets/app/js/controllers/aboutCodeJsTree.js, test/aboutCodeDB.test.js
=> Add jstree coloring for scancode packages #26

assets/app/css/main.css, assets/app/js/aboutCodeDB.js, assets/app/js/controllers/aboutCodeJsTree.js, assets/app/js/controllers/conclusionDialog.js
* Refactor JSTree data handling code
* Add 4 new conclusion icon color definitions
* Open/close folder icons change colors correctly
* Update JSTree sort function to account for new types
* Change JSTree marker to correct Conclusion value on the fly
Addresses #209
=> Add Conclusion markers for the JSTree

assets/app/js/renderer.js
=> Default SQLite filename mirrors JSON filename #304

assets/app/js/controllers/aboutCodeScanDataTable.js
* Add new File info column group
* Make File info columns the default on load
* Add mime_type and file_type to Origin column group
* Remove URL columns from License info column group
* Remove homepage/download URL from package column group
Addresses: #272
=> Refine ScanData view column groups

assets/app/js/controllers/aboutCodeScanDataTable.js
=> Programming language and file name now being filtered correctly #320

assets/app/js/aboutCodeDB.js, test/aboutCodeDB.test.js, test/data/aboutcodeDB/2.9.8-header.json, test/data/aboutcodeDB/legacy-header.json
=> Grab scanfile header infomation in new format #323

assets/app/js/aboutCodeDB.js, assets/app/js/models/flatFile.js
=> purl handling hotfix

assets/app/js/controllers/scanDataTable.js
=> Global search box cleared before drill down #327

assets/app/js/controllers/dashboard.js, assets/app/js/helpers/utils.js
=> Package type bar chart now working #315

assets/app/js/controllers/jsTree.js
=> Table view (and all other views) now refresh with a new import #293

assets/app/js/controllers/welcomePage.js, assets/app/js/renderer.js, index.html
* Add basic button layout to handle basic functions
* Clean up sidebar buttons and move functionality to Welcome Page
Addresses: #290, #306
=> Add Welcome Page

assets/app/js/helpers/utils.js
=> Fix broken barchart counts #285

assets/app/css/main.css, assets/app/js/renderer.js
=> Dashboard view now shows current selected path #336

assets/app/js/workbenchDB.js
=> Properly warn when importing scan with no file info option #266

assets/app/js/controllers/dashboard.js
=> Dashboard now correctly lists number of files scanned #347

assets/app/js/controllers/barChart.js
=> Fix barchat package attribute counts #344

assets/app/js/controllers/scanDataTable.js
=> Add Type to File Info and Default columnset #164

assets/app/js/renderer.js, main.js
fixes #356.
Used
Ctrl + = for zoom in 
Ctrl + - for zoom out
Ctrl + 0 for zoom reset
=> add option to zoom in, out and reset

assets/app/css/main.css, assets/app/js/controllers/jsTree.js, assets/app/js/controllers/scanDataTable.js, assets/app/js/models/database.js, assets/app/js/models/flatFile.js, assets/app/js/models/licensePolicy.js, assets/app/js/workbenchDB.js
* Add licensePolicy model
* Add inital jstree license policy icons and colors
Addresses: #215
=> Add License Policy support

assets/app/js/controllers/scanDataTable.js, assets/app/js/renderer.js
=> Add Reset Filters button #353

assets/app/js/controllers/scanDataTable.js
=> Properly escape underscore characters in Global Search

assets/app/js/controllers/conclusionDataTable.js, assets/app/js/controllers/conclusionDialog.js, assets/app/js/models/conclusion.js
* Add purl field to Conclusions model
* Add Package URL column to Conclusions DataTable
* Automatically populate purl values for concluded packages
Addresses: #337
=> Add pURL support for Conclusions

.travis.yml, appveyor.yml
=> Upload Workbench builds to SorceForge

npm-shrinkwrap.json
=> Security fix via npm audit

assets/app/css/main.css, assets/app/js/controllers/scanDataTable.js
* Convert to fixed table
* Handle dynamic ellipsis overflow
* Add mouse hover functionality to long strings
Addresses: #253
=> Keep horizontal scroll pos when switching pages

assets/app/js/controllers/fileDashboard.js, assets/app/js/controllers/licenseDashboard.js, assets/app/js/controllers/packageDashboard.js
=> Show "No Value Detected" items by default on chart

assets/app/js/workbenchDB.js
=> Fix directory size bug

assets/app/js/controllers/dejacodeExportDialog.js, assets/app/js/renderer.js, index.html, npm-shrinkwrap.json, package.json
* Add button to toggle DejaCode API key visibility
* Trim leading and trailing spaces from DejaCode API key
* Allow empty Product Version in DejaCode upload form
* Fix npm vulns via `npm audit`
Addresses: #391, #392
=> Improve Conclusion uploads
